// <auto-generated />
using Blockchain_example.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Blockchain_example.Migrations
{
    [DbContext(typeof(BlockChainDbContext))]
    [Migration("20171129193554_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("Blockchain_example.Blockchain.Block", b =>
                {
                    b.Property<int>("Index")
                        .ValueGeneratedOnAdd();

                    b.Property<byte[]>("Data");

                    b.Property<string>("Hash");

                    b.Property<string>("PrevHash");

                    b.Property<DateTime>("Timestamp");

                    b.HasKey("Index");

                    b.ToTable("Blocks");
                });
#pragma warning restore 612, 618
        }
    }
}
